export const keywordMap = {
  // 기술 카테고리
  '프론트엔드 개발':
    /html|css|javascript|react|vue|angular|next\.js|svelte|웹개발|프론트엔드|UI|UX|DOM|웹팩|바벨|JSX|TSX|타입스크립트|scss|sass/i,
  '백엔드 개발':
    /서버|api|node\.js|express|spring|django|nestjs|laravel|ruby on rails|백엔드|서버사이드|REST|jwt|인증|미들웨어|마이크로서비스|컨트롤러|서비스|레포지토리/i,
  '클라우드 & DevOps':
    /aws|azure|gcp|docker|kubernetes|ci\/cd|jenkins|github actions|terraform|클라우드|devops|배포|인프라|kubelet|파드|컨테이너|오케스트레이션|서버리스|lambda/i,
  데이터베이스:
    /sql|nosql|mysql|postgresql|mongodb|redis|graphql|orm|쿼리|데이터베이스|인덱스|트랜잭션|정규화|조인|인덱싱|샤딩|파티셔닝|캐싱|스키마/i,
  '데이터 분석':
    /데이터|시각화|통계|pandas|tableau|python|r|빅데이터|데이터 파이프라인|분석|머신러닝|딥러닝|데이터 마이닝|시계열|회귀분석|히스토그램|상관관계|csv|엑셀|스프레드시트/i,
  '모바일 앱 개발':
    /android|ios|flutter|react native|swift|kotlin|모바일|앱|어플리케이션|모바일앱|네이티브앱|하이브리드앱|앱스토어|구글플레이|푸시알림|모바일 UI|앱 개발/i,
  인공지능:
    /ai|머신러닝|딥러닝|tensorflow|pytorch|llm|자연어|처리|인공지능|신경망|cnn|rnn|lstm|분류|회귀|강화학습|지도학습|비지도학습|모델|훈련|테스트|검증|예측/i,
  '게임 개발':
    /unity|unreal engine|게임|엔진|3d|렌더링|게임 프로그래밍|게임 개발|게임 디자인|레벨 디자인|게임 메카닉|물리엔진|애니메이션|스프라이트|2d|3d|게임 서버/i,
  블록체인:
    /암호화폐|web3|ethereum|solidity|스마트 컨트랙트|nft|블록체인|비트코인|이더리움|코인|토큰|지갑|채굴|합의 알고리즘|분산원장|dapp|dao|defi/i,
  보안: /보안|해킹|침투|테스트|암호화|인증|권한|사이버보안|취약점|pen test|방화벽|ssl|tls|vpn|ids|ips|보안 감사|cve|취약점|zero day|악성코드/i,
  네트워크:
    /tcp\/ip|osi|라우팅|스위칭|프록시|vpn|로드 밸런싱|네트워크|패킷|dns|http|https|ftp|ssh|소켓|서브넷|nat|dhcp|라우터|스위치|네트워크 토폴로지/i,
  '시스템 & 운영체제':
    /리눅스|윈도우|macos|커널|프로세스|스레드|파일 시스템|가상화|운영체제|os|유닉스|쉘|bash|파워쉘|터미널|명령어|시스템콜|메모리관리|프로세스관리/i,
  '개발 도구':
    /ide|터미널|git|github|vs code|docker compose|npm|yarn|webpack|개발 도구|버전 관리|형상 관리|빌드 도구|패키지 매니저|린트|테스트 도구|디버깅|에디터|통합개발환경/i,
  알고리즘:
    /자료구조|정렬|검색|그래프|알고리즘|복잡도|시간복잡도|공간복잡도|big o|재귀|동적계획법|그리디|분할정복|백트래킹|해시|트리|스택|큐|힙|우선순위큐/i,

  // 경제 카테고리
  '창업 & 스타트업':
    /창업|스타트업|벤처|투자유치|엑셀러레이터|인큐베이터|시드|엔젤|피치|비즈니스모델|pmf|사업계획|mvp|린스타트업|스케일업|유니콘|데모데이|밸류에이션/i,
  '마케팅 & 광고':
    /마케팅|광고|브랜딩|seo|sem|디지털마케팅|그로스해킹|sns마케팅|콘텐츠마케팅|퍼포먼스마케팅|바이럴|인플루언서|cpc|ctr|전환율|ab테스트|타겟팅|퍼널/i,
  '금융 & 투자':
    /금융|투자|주식|채권|펀드|재테크|금융상품|주식시장|증권|코인|암호화폐|etf|리스크|수익률|포트폴리오|원금|이자|배당|연금|보험|대출|신용|자산관리/i,
  '경영 전략':
    /경영|전략|비즈니스모델|ceo|리더십|조직문화|혁신|성과|kpi|의사결정|경영진|swot|경쟁우위|시장점유율|기업가치|성장전략|중장기전략|사업다각화|합병|인수|사업확장/i,
  전자상거래:
    /이커머스|쇼핑몰|온라인쇼핑|플랫폼비즈니스|옴니채널|d2c|물류|결제|커머스|상품|판매|구매|장바구니|배송|재고|결제시스템|pms|cms|고객관리|마진|매출|입점|셀러/i,
  부동산:
    /부동산|임대|매매|전세|월세|아파트|오피스텔|부동산시장|청약|입주|분양|재건축|재개발|임대수익|공시지가|시세|담보대출|중개|부동산경매|투자수익률|상가|오피스|토지/i,
  '인사 & 조직 관리':
    /인사|채용|조직관리|hr|인재|평가|보상|노무|근로계약|복리후생|조직문화|인력관리|인적자원|성과평가|교육훈련|경력개발|리더십|팀빌딩|조직개발|퇴직|해고|고용/i,

  // 디자인 카테고리
  '그래픽 디자인':
    /포토샵|일러스트레이터|디자인|원칙|타이포그래피|로고|브랜딩|그래픽|시각디자인|편집디자인|패키지디자인|cmyk|rgb|벡터|래스터|픽셀|해상도|인쇄|출력|색상/i,
  'UI/UX 디자인':
    /사용자|경험|인터페이스|와이어프레임|프로토타입|사용성|테스트|피그마|스케치|ui|ux|유저플로우|인터랙션|디자인시스템|페르소나|사용자여정|a\/b테스트|반응형|접근성/i,
  '사진 & 영상':
    /사진|촬영|편집|영상제작|촬영기법|조명|카메라|프리미어|애프터이펙트|렌즈|구도|노출|셔터스피드|조리개|iso|white balance|컬러그레이딩|영상편집|컷|트랜지션/i,
  일러스트레이션:
    /드로잉|디지털|아트|캐릭터|디자인|그림|페인팅|만화|일러스트|스케치|컨셉아트|타블렛|프로크리에이트|색채|명암|구도|스타일라이징|원화|드로잉테크닉|브러시/i,
  애니메이션:
    /모션|그래픽|3d|애니메이션|스톱모션|캐릭터|애니메이팅|기법|애니메이터|키프레임|타이밍|이징|모션그래픽|리깅|더빙|립싱크|스크립트|스토리보드|애니메이틱/i,
  '산업 디자인':
    /제품|디자인|가구|공간|프로토타이핑|3d|모델링|cad|인더스트리얼|디자인|제품디자인|렌더링|목업|설계|엔지니어링|소재|제조|양산|디테일|기능성|사용성|인체공학/i,
  '패션 디자인':
    /의류|디자인|패션|트렌드|패턴|메이킹|소재|컬렉션|스타일링|의류디자인|패션디자인|봉제|재단|패턴|실루엣|텍스타일|트렌드|코디네이션|룩북|시즌|컬러|스타일/i,

  // 교육 & 학습 카테고리
  '온라인 강의':
    /이러닝|교육|콘텐츠|강의|플랫폼|학습|방법론|온라인|코스|mooc|강의자료|학습관리|lms|웨비나|튜토리얼|교육과정|커리큘럼|학습동기|학습효과|온라인교육|화상강의/i,
  '코딩 & 프로그래밍':
    /프로그래밍|교육|코딩|입문|알고리즘|학습|개발자|학습경로|코딩교육|프로그래밍언어|개발환경|디버깅|컴퓨팅사고력|문제해결|로직|파이썬|자바|자바스크립트/i,
  '언어 학습':
    /영어|제2외국어|어학공부|어휘|회화|문법|발음|언어교환|외국어|학습법|영어공부|영어회화|토익|토플|ielts|번역|통역|언어학|언어습득|어학연수|영어독해|영작/i,
  자기계발:
    /생산성|습관형성|시간관리|마인드셋|목표설정|독서법|학습법|자기계발|자기혁신|성장|자기관리|동기부여|의지력|목표달성|성공습관|자기성찰|심리학|행동변화|긍정적사고/i,
  '학술 & 연구':
    /학술논문|연구방법론|학문분야|인용|논문작성|연구동향|학위과정|학술|연구|학술저널|학회|학술대회|학술활동|인용방식|apa|mla|연구윤리|실험설계|통계분석|가설검증/i,
  '자격증 및 시험 준비':
    /공인시험|자격증|시험전략|문제풀이|수험정보|준비방법|시험|자격검정|수험생|기출문제|모의고사|합격전략|시험일정|커트라인|면접|실기|필기|자격시험|문제은행/i,

  // 취미 카테고리
  '영화 & 드라마':
    /영화|리뷰|드라마|분석|감상평|추천|배우|감독|스트리밍|콘텐츠|영화평론|시나리오|촬영|연출|장르|액션|코미디|스릴러|로맨스|공포|SF|판타지|다큐|시리즈/i,
  '음악 & 팟캐스트':
    /음악|추천|앨범|리뷰|아티스트|플레이리스트|팟캐스트|콘텐츠|오디오|노래|장르|가수|작곡|작사|프로듀싱|믹싱|마스터링|보컬|악기|공연|음반|음원|팟캐스트에피소드/i,
  '게임 리뷰':
    /게임|평가|플레이|후기|게임|추천|e스포츠|게이밍|콘솔|pc게임|게임리뷰|게임분석|게임플레이|rpg|fps|mmorpg|스토리|그래픽|사운드|난이도|게임성|멀티플레이|싱글플레이/i,
  '웹툰 & 만화':
    /웹툰|리뷰|만화|추천|작가|작품분석|코믹스|일본|만화|웹툰|플랫폼|만화리뷰|웹툰리뷰|스토리|그림체|연재|회차|캐릭터|장르|순위|인기웹툰|네이버웹툰|카카오웹툰/i,
  '유튜브 & 스트리밍':
    /유튜버|스트리머|콘텐츠|크리에이터|방송|트위치|쇼츠|라이브|유튜브|채널|구독자|시청자|영상콘텐츠|스트리밍방송|방송장비|편집|썸네일|채널운영|수익화|알고리즘/i,
  '이벤트 & 페스티벌':
    /공연|콘서트|축제|전시회|행사|컨퍼런스|콘벤션|모임|이벤트|페스티벌|공연정보|예매|티켓|라인업|아티스트|전시|박람회|갤러리|뮤지엄|문화행사|지역축제/i,

  // 여가 카테고리
  '요리 & 레시피':
    /요리법|레시피|음식|베이킹|쿠킹|식재료|주방기구|다이닝|요리|조리법|요리팁|레시피|식품|식자재|조리도구|주방용품|베이킹|제과제빵|홈쿠킹|맛집|푸드|다이닝/i,
  '건강 & 피트니스':
    /운동|헬스|다이어트|영양|웰빙|요가|명상|건강관리|피트니스|체중관리|건강식단|근력운동|유산소|스트레칭|헬스장|홈트레이닝|식단관리|영양섭취|건강검진|의학/i,
  '패션 & 뷰티':
    /패션|트렌드|스타일링|코디|메이크업|스킨케어|화장품|헤어스타일|패션|뷰티|코디네이션|스타일|메이크업|스킨케어|화장품|헤어|네일|패션아이템|뷰티팁|트렌드/i,
  자동차:
    /자동차|리뷰|시승기|차량|정보|구매|가이드|정비|튜닝|오토바이|자동차리뷰|신차|중고차|차량관리|주행|엔진|배기량|연비|성능|외관|내장|옵션|제원|시승|시승기/i,
  스포츠:
    /스포츠|뉴스|경기|결과|팀|선수|축구|야구|농구|골프|테니스|스포츠경기|스포츠뉴스|스포츠팀|리그|토너먼트|스포츠선수|스포츠기록|스포츠용품|스포츠분석|스포츠베팅/i,
  '독서 & 서평':
    /책|리뷰|독서|추천|작가|출판|문학|신간|독서|모임|서평|독서|책리뷰|작가|출판사|문학작품|소설|시|에세이|자기계발서|인문학|과학|역사|고전|신간|베스트셀러/i,
  인테리어:
    /홈|인테리어|가구|인테리어|소품|집꾸미기|홈스타일링|리모델링|인테리어|홈데코|가구|소품|인테리어디자인|공간활용|리빙|홈스타일링|인테리어팁|인테리어소품|가구배치/i,

  // 뉴스 카테고리
  '국내 뉴스':
    /국내|시사|보도|이슈|속보|한국|뉴스|지역|소식|국내뉴스|국내소식|국내이슈|사회|정치|경제|문화|지역뉴스|뉴스속보|이슈분석|사건사고|정책|법원|검찰|경찰/i,
  '국제 뉴스':
    /해외|소식|국제|정세|글로벌|이슈|외신|국제관계|해외|뉴스|국제뉴스|해외소식|국제이슈|글로벌뉴스|외신보도|세계정세|국제관계|국제분쟁|외교|글로벌경제|해외정책/i,
  'IT/테크 뉴스':
    /기술|뉴스|it|동향|신제품|기술|트렌드|테크|이슈|디지털|뉴스|테크뉴스|IT동향|신기술|기술소식|제품출시|it기업|기술트렌드|테크산업|디지털혁신|가젯|디바이스/i,
  정치: /정치|뉴스|국회|정당|선거|정책|법안|정치인|정치|분석|정치소식|정치인|정당|선거|투표|법안|정치분석|정책|국회|청와대|여야|정치이슈|정치동향|정치뉴스|정치인인터뷰/i,
  '사회 이슈':
    /사회문제|환경|인권|노동|교육|젠더|다양성|사회|현상|사회이슈|사회문제|사회현상|환경문제|인권|노동|교육|젠더|다양성|사회갈등|사회운동|사회정책|사회분석|사회조사/i,

  // 기타
  기타: /기타|분류불가|기타주제|기타분야|기타콘텐츠|기타정보|기타자료|기타서비스|잡다|분류안됨|혼합|다양|여러주제|복합적|다목적|복합성|혼합콘텐츠|일반|일반적|무분류/i,
};

export const domainKeywords = {
  // 기술 카테고리
  '프론트엔드 개발': [
    'react',
    'vue',
    'angular',
    'frontend',
    'javascript',
    'webdev',
    'html',
    'css',
    'typescript',
  ],
  '백엔드 개발': [
    'backend',
    'server',
    'api',
    'nodejs',
    'express',
    'spring',
    'django',
    'nestjs',
    'laravel',
    'rails',
  ],
  '클라우드 & DevOps': [
    'aws',
    'azure',
    'gcp',
    'cloud',
    'docker',
    'kubernetes',
    'devops',
    'cicd',
    'jenkins',
    'terraform',
  ],
  데이터베이스: [
    'mysql',
    'postgresql',
    'mongodb',
    'redis',
    'database',
    'sql',
    'nosql',
    'graphql',
    'orm',
  ],
  '데이터 분석': [
    'data',
    'analytics',
    'visualization',
    'pandas',
    'tableau',
    'bigdata',
    'dataengineering',
  ],
  '모바일 앱 개발': [
    'android',
    'ios',
    'flutter',
    'reactnative',
    'swift',
    'kotlin',
    'mobiledev',
    'mobileapp',
  ],
  인공지능: [
    'ai',
    'machinelearning',
    'deeplearning',
    'tensorflow',
    'pytorch',
    'nlp',
    'artificialintelligence',
  ],
  '게임 개발': [
    'unity',
    'unrealengine',
    'gamedev',
    'gamedevelopment',
    'gaming',
    '3d',
    'rendering',
  ],
  블록체인: [
    'blockchain',
    'crypto',
    'ethereum',
    'solidity',
    'web3',
    'nft',
    'smartcontract',
  ],
  보안: [
    'security',
    'hacking',
    'pentest',
    'cybersecurity',
    'encryption',
    'authentication',
  ],
  네트워크: [
    'network',
    'networking',
    'tcp',
    'ip',
    'routing',
    'switching',
    'proxy',
    'vpn',
    'loadbalancing',
  ],
  '시스템 & 운영체제': [
    'linux',
    'windows',
    'macos',
    'os',
    'unix',
    'kernel',
    'process',
    'thread',
    'filesystem',
  ],
  '개발 도구': [
    'git',
    'github',
    'vscode',
    'ide',
    'terminal',
    'npm',
    'yarn',
    'docker',
    'webpack',
  ],
  알고리즘: [
    'algorithm',
    'datastructure',
    'sorting',
    'searching',
    'graph',
    'complexity',
    'bigo',
  ],

  // 경제 카테고리
  '창업 & 스타트업': [
    'startup',
    'venture',
    'entrepreneur',
    'startupweekly',
    'angellist',
    'ycombinator',
    'techcrunch',
  ],
  '마케팅 & 광고': [
    'marketing',
    'advertising',
    'seo',
    'sem',
    'digitalmarketing',
    'branding',
    'growthhacking',
  ],
  '금융 & 투자': [
    'finance',
    'investment',
    'stock',
    'stocks',
    'investing',
    'trading',
    'finance',
    'fintech',
    'wealth',
  ],
  '경영 전략': [
    'business',
    'strategy',
    'management',
    'leadership',
    'enterprise',
    'company',
    'corporate',
  ],
  전자상거래: [
    'ecommerce',
    'shopping',
    'retail',
    'marketplace',
    'shopify',
    'amazon',
    'ebay',
    'onlinestore',
  ],
  부동산: [
    'realestate',
    'property',
    'housing',
    'mortgage',
    'rent',
    'apartment',
    'housing',
    'construction',
  ],
  '인사 & 조직 관리': [
    'hr',
    'humanresources',
    'recruitment',
    'talent',
    'hiring',
    'organization',
    'workforce',
  ],

  // 디자인 카테고리
  '그래픽 디자인': [
    'graphic',
    'design',
    'photoshop',
    'illustrator',
    'typography',
    'logo',
    'branding',
  ],
  'UI/UX 디자인': [
    'ui',
    'ux',
    'userexperience',
    'userinterface',
    'figma',
    'sketch',
    'prototype',
    'wireframe',
  ],
  '사진 & 영상': [
    'photo',
    'photography',
    'video',
    'film',
    'camera',
    'premiere',
    'aftereffects',
    'editing',
  ],
  일러스트레이션: [
    'illustration',
    'drawing',
    'art',
    'character',
    'digital',
    'painting',
    'sketch',
    'comic',
  ],
  애니메이션: [
    'animation',
    'motion',
    'motiongraphics',
    '3d',
    'character',
    'stopmotion',
    'anime',
    'cartoon',
  ],
  '산업 디자인': [
    'industrial',
    'product',
    'design',
    'furniture',
    'space',
    'prototype',
    '3d',
    'modeling',
    'cad',
  ],
  '패션 디자인': [
    'fashion',
    'clothing',
    'style',
    'trend',
    'pattern',
    'textile',
    'collection',
    'apparel',
  ],

  // 교육 & 학습 카테고리
  '온라인 강의': [
    'course',
    'lecture',
    'education',
    'learning',
    'online',
    'mooc',
    'elearning',
    'tutorial',
  ],
  '코딩 & 프로그래밍': [
    'coding',
    'programming',
    'learn',
    'tutorial',
    'beginner',
    'code',
    'classroom',
    'lesson',
  ],
  '언어 학습': [
    'language',
    'english',
    'korean',
    'spanish',
    'japanese',
    'french',
    'chinese',
    'duolingo',
  ],
  자기계발: [
    'selfimprovement',
    'productivity',
    'habit',
    'timemanagement',
    'mindset',
    'goal',
    'motivation',
  ],
  '학술 & 연구': [
    'academic',
    'research',
    'scientific',
    'journal',
    'scholar',
    'paper',
    'thesis',
    'dissertation',
  ],
  '자격증 및 시험 준비': [
    'certification',
    'exam',
    'test',
    'preparation',
    'study',
    'practice',
    'question',
    'quiz',
  ],

  // 취미 카테고리
  '영화 & 드라마': [
    'movie',
    'film',
    'drama',
    'series',
    'cinema',
    'review',
    'netflix',
    'hulu',
    'disney',
  ],
  '음악 & 팟캐스트': [
    'music',
    'podcast',
    'song',
    'album',
    'artist',
    'playlist',
    'spotify',
    'apple',
    'sound',
  ],
  '게임 리뷰': [
    'game',
    'gaming',
    'review',
    'playstation',
    'xbox',
    'nintendo',
    'steam',
    'esports',
    'gamer',
  ],
  '웹툰 & 만화': [
    'webtoon',
    'comic',
    'manga',
    'manhwa',
    'manhua',
    'naver',
    'kakao',
    'line',
    'tapas',
  ],
  '유튜브 & 스트리밍': [
    'youtube',
    'streamer',
    'content',
    'creator',
    'broadcast',
    'twitch',
    'shorts',
    'live',
  ],
  '이벤트 & 페스티벌': [
    'event',
    'festival',
    'concert',
    'exhibition',
    'conference',
    'convention',
    'meetup',
    'show',
  ],

  // 여가 카테고리
  '요리 & 레시피': [
    'cooking',
    'recipe',
    'food',
    'baking',
    'kitchen',
    'ingredient',
    'chef',
    'dish',
    'meal',
  ],
  '건강 & 피트니스': [
    'health',
    'fitness',
    'workout',
    'diet',
    'nutrition',
    'exercise',
    'wellness',
    'gym',
    'yoga',
  ],
  '패션 & 뷰티': [
    'fashion',
    'beauty',
    'style',
    'makeup',
    'skincare',
    'cosmetics',
    'hair',
    'outfit',
    'trend',
  ],
  자동차: [
    'car',
    'automotive',
    'vehicle',
    'review',
    'drive',
    'motor',
    'auto',
    'carreview',
    'driving',
  ],
  스포츠: [
    'sports',
    'football',
    'soccer',
    'basketball',
    'baseball',
    'tennis',
    'golf',
    'nba',
    'mlb',
    'nfl',
  ],
  '독서 & 서평': [
    'book',
    'reading',
    'review',
    'author',
    'literature',
    'novel',
    'bookclub',
    'goodreads',
  ],
  인테리어: [
    'interior',
    'home',
    'furniture',
    'decor',
    'decoration',
    'homedecor',
    'homedesign',
    'remodeling',
  ],
  // 뉴스 카테고리
  '국내 뉴스': [
    'news',
    'korea',
    'korean',
    'domestic',
    'local',
    'jtbc',
    'kbs',
    'mbc',
    'sbs',
    'ytn',
    'yonhap',
  ],
  '국제 뉴스': [
    'world',
    'international',
    'global',
    'foreign',
    'overseas',
    'bbc',
    'cnn',
    'reuters',
    'ap',
    'afp',
  ],
  'IT/테크 뉴스': [
    'tech',
    'technews',
    'technology',
    'gadget',
    'innovation',
    'techtrend',
    'techcrunch',
    'wired',
    'theverge',
    'digitaltrend',
    'ittimes',
  ],
  정치: [
    'politics',
    'political',
    'government',
    'election',
    'policy',
    'congress',
    'parliament',
    'legislation',
    'politician',
    'democracy',
    'republican',
    'democrat',
  ],
  '사회 이슈': [
    'social',
    'society',
    'issue',
    'environment',
    'climate',
    'humanrights',
    'equality',
    'discrimination',
    'activism',
    'socialmovement',
    'justice',
    'civilrights',
  ],
  // 기타
  기타: [
    'misc',
    'miscellaneous',
    'other',
    'etc',
    'various',
    'general',
    'random',
    'diverse',
    'mixed',
    'unclassified',
    'uncategorized',
  ],
};

export const pathKeywords = {
  // 기술 카테고리
  '프론트엔드 개발': [
    '/frontend',
    '/web-development',
    '/react',
    '/javascript',
    '/typescript',
    '/html-css',
    '/vue',
    '/angular',
    '/frontend-frameworks',
  ],
  '백엔드 개발': [
    '/backend',
    '/server',
    '/api',
    '/nodejs',
    '/spring',
    '/django',
    '/php',
    '/nestjs',
    '/laravel',
    '/ruby-rails',
  ],
  '클라우드 & DevOps': [
    '/cloud',
    '/devops',
    '/aws',
    '/azure',
    '/gcp',
    '/docker',
    '/kubernetes',
    '/cicd',
    '/jenkins',
    '/terraform',
  ],
  데이터베이스: [
    '/database',
    '/sql',
    '/nosql',
    '/mysql',
    '/postgresql',
    '/mongodb',
    '/redis',
    '/graphql',
    '/orm',
    '/db-optimization',
  ],
  '데이터 분석': [
    '/data-analytics',
    '/data-science',
    '/visualization',
    '/pandas',
    '/tableau',
    '/bigdata',
    '/data-engineering',
    '/statistics',
    '/data-mining',
  ],
  '모바일 앱 개발': [
    '/mobile',
    '/android',
    '/ios',
    '/flutter',
    '/react-native',
    '/swift',
    '/kotlin',
    '/mobile-development',
    '/app-development',
  ],
  인공지능: [
    '/ai',
    '/machine-learning',
    '/deep-learning',
    '/tensorflow',
    '/pytorch',
    '/nlp',
    '/computer-vision',
    '/neural-networks',
    '/ml',
  ],
  '게임 개발': [
    '/gamedev',
    '/unity',
    '/unreal-engine',
    '/game-development',
    '/3d-game',
    '/game-programming',
    '/game-engine',
    '/level-design',
  ],
  블록체인: [
    '/blockchain',
    '/crypto',
    '/web3',
    '/ethereum',
    '/solidity',
    '/smart-contracts',
    '/nft',
    '/defi',
    '/bitcoin',
  ],
  보안: [
    '/security',
    '/cybersecurity',
    '/hacking',
    '/pentest',
    '/encryption',
    '/infosec',
    '/network-security',
    '/appsec',
    '/vulnerability',
  ],
  네트워크: [
    '/network',
    '/networking',
    '/tcpip',
    '/routing',
    '/switching',
    '/proxy',
    '/vpn',
    '/load-balancing',
    '/dns',
  ],
  '시스템 & 운영체제': [
    '/system',
    '/os',
    '/linux',
    '/windows',
    '/macos',
    '/kernel',
    '/bash',
    '/shell',
    '/file-system',
    '/virtualization',
  ],
  '개발 도구': [
    '/dev-tools',
    '/git',
    '/github',
    '/vscode',
    '/ide',
    '/terminal',
    '/npm',
    '/yarn',
    '/webpack',
    '/debugging',
  ],
  알고리즘: [
    '/algorithms',
    '/data-structures',
    '/problem-solving',
    '/sorting',
    '/searching',
    '/graph-algorithms',
    '/dynamic-programming',
    '/complexity',
  ],

  // 경제 카테고리
  '창업 & 스타트업': [
    '/startup',
    '/entrepreneurship',
    '/venture',
    '/founder',
    '/funding',
    '/incubator',
    '/accelerator',
    '/seed-funding',
    '/series-a',
  ],
  '마케팅 & 광고': [
    '/marketing',
    '/advertising',
    '/digital-marketing',
    '/seo',
    '/sem',
    '/social-media-marketing',
    '/content-marketing',
    '/branding',
  ],
  '금융 & 투자': [
    '/finance',
    '/investment',
    '/stock',
    '/stocks',
    '/trading',
    '/investing',
    '/fintech',
    '/wealth-management',
    '/personal-finance',
  ],
  '경영 전략': [
    '/business-strategy',
    '/management',
    '/leadership',
    '/corporate',
    '/enterprise',
    '/strategic-planning',
    '/business-model',
    '/operational-excellence',
  ],
  전자상거래: [
    '/ecommerce',
    '/online-retail',
    '/marketplace',
    '/shopify',
    '/amazon',
    '/ebay',
    '/online-store',
    '/d2c',
    '/retail-tech',
  ],
  부동산: [
    '/real-estate',
    '/property',
    '/housing',
    '/realty',
    '/apartment',
    '/commercial-property',
    '/mortgage',
    '/rent',
    '/construction',
  ],
  '인사 & 조직 관리': [
    '/hr',
    '/human-resources',
    '/recruitment',
    '/talent',
    '/hiring',
    '/organization',
    '/workforce',
    '/team-management',
    '/employee-engagement',
  ],

  // 디자인 카테고리
  '그래픽 디자인': [
    '/graphic-design',
    '/design',
    '/photoshop',
    '/illustrator',
    '/typography',
    '/logo-design',
    '/branding',
    '/visual-design',
  ],
  'UI/UX 디자인': [
    '/ui',
    '/ux',
    '/user-experience',
    '/user-interface',
    '/figma',
    '/sketch',
    '/prototype',
    '/wireframe',
    '/interaction-design',
  ],
  '사진 & 영상': [
    '/photography',
    '/video',
    '/filming',
    '/camera',
    '/premiere',
    '/after-effects',
    '/video-editing',
    '/cinematography',
    '/lighting',
  ],
  일러스트레이션: [
    '/illustration',
    '/drawing',
    '/digital-art',
    '/character-design',
    '/concept-art',
    '/painting',
    '/sketch',
    '/procreate',
  ],
  애니메이션: [
    '/animation',
    '/motion-graphics',
    '/3d-animation',
    '/character-animation',
    '/stop-motion',
    '/motion',
    '/anime',
    '/motion-design',
  ],
  '산업 디자인': [
    '/industrial-design',
    '/product-design',
    '/furniture-design',
    '/space-design',
    '/3d-modeling',
    '/cad',
    '/prototyping',
    '/manufacturing',
  ],
  '패션 디자인': [
    '/fashion-design',
    '/clothing',
    '/fashion',
    '/style',
    '/apparel',
    '/textile',
    '/pattern-making',
    '/collection',
    '/trend',
  ],

  // 교육 & 학습 카테고리
  '온라인 강의': [
    '/online-course',
    '/e-learning',
    '/mooc',
    '/lecture',
    '/education',
    '/learning-platform',
    '/tutorial',
    '/online-education',
  ],
  '코딩 & 프로그래밍': [
    '/coding',
    '/programming',
    '/learn-to-code',
    '/beginner-programming',
    '/code-tutorial',
    '/coding-bootcamp',
    '/programming-lesson',
  ],
  '언어 학습': [
    '/language-learning',
    '/english',
    '/korean',
    '/japanese',
    '/chinese',
    '/spanish',
    '/french',
    '/duolingo',
    '/language-exchange',
  ],
  자기계발: [
    '/self-improvement',
    '/productivity',
    '/habit-formation',
    '/time-management',
    '/mindset',
    '/goal-setting',
    '/motivation',
    '/personal-growth',
  ],
  '학술 & 연구': [
    '/academic',
    '/research',
    '/scholarly',
    '/journal',
    '/paper',
    '/thesis',
    '/dissertation',
    '/scientific-research',
    '/academia',
  ],
  '자격증 및 시험 준비': [
    '/certification',
    '/exam-prep',
    '/test-preparation',
    '/study-guide',
    '/practice-test',
    '/mock-exam',
    '/qualification',
    '/license',
  ],

  // 취미 카테고리
  '영화 & 드라마': [
    '/movie',
    '/film',
    '/drama',
    '/series',
    '/cinema',
    '/netflix',
    '/hulu',
    '/disney-plus',
    '/tv-shows',
    '/film-review',
  ],
  '음악 & 팟캐스트': [
    '/music',
    '/podcast',
    '/song',
    '/album',
    '/artist',
    '/spotify',
    '/apple-music',
    '/playlist',
    '/audio',
    '/music-review',
  ],
  '게임 리뷰': [
    '/game',
    '/gaming',
    '/game-review',
    '/playstation',
    '/xbox',
    '/nintendo',
    '/steam',
    '/pc-gaming',
    '/esports',
    '/game-critique',
  ],
  '웹툰 & 만화': [
    '/webtoon',
    '/comic',
    '/manga',
    '/manhwa',
    '/manhua',
    '/naver-webtoon',
    '/kakao-webtoon',
    '/line-webtoon',
    '/comic-review',
  ],
  '유튜브 & 스트리밍': [
    '/youtube',
    '/streamer',
    '/content-creator',
    '/twitch',
    '/live-stream',
    '/vlogger',
    '/youtube-channel',
    '/streaming-platform',
    '/shorts',
  ],
  '이벤트 & 페스티벌': [
    '/event',
    '/festival',
    '/concert',
    '/exhibition',
    '/conference',
    '/convention',
    '/meetup',
    '/show',
    '/expo',
    '/performance',
  ],

  // 여가 카테고리
  '요리 & 레시피': [
    '/cooking',
    '/recipe',
    '/food',
    '/baking',
    '/cuisine',
    '/chef',
    '/kitchen',
    '/cooking-tips',
    '/meal-prep',
    '/ingredients',
  ],
  '건강 & 피트니스': [
    '/health',
    '/fitness',
    '/workout',
    '/diet',
    '/nutrition',
    '/exercise',
    '/wellness',
    '/gym',
    '/yoga',
    '/weight-loss',
  ],
  '패션 & 뷰티': [
    '/fashion',
    '/beauty',
    '/style',
    '/makeup',
    '/skincare',
    '/cosmetics',
    '/hair',
    '/outfit',
    '/fashion-trend',
    '/beauty-tips',
  ],
  자동차: [
    '/car',
    '/automotive',
    '/vehicle',
    '/car-review',
    '/auto',
    '/motor',
    '/test-drive',
    '/driving',
    '/automobile',
    '/car-buying',
  ],
  스포츠: [
    '/sports',
    '/football',
    '/soccer',
    '/basketball',
    '/baseball',
    '/tennis',
    '/golf',
    '/nba',
    '/mlb',
    '/nfl',
    '/sports-news',
  ],
  '독서 & 서평': [
    '/book',
    '/reading',
    '/book-review',
    '/author',
    '/literature',
    '/novel',
    '/book-club',
    '/book-recommendation',
    '/goodreads',
  ],
  인테리어: [
    '/interior',
    '/home-decor',
    '/furniture',
    '/decoration',
    '/interior-design',
    '/home-styling',
    '/remodeling',
    '/home-improvement',
    '/interior-inspiration',
  ],

  // 뉴스 카테고리
  '국내 뉴스': [
    '/news',
    '/korea-news',
    '/korean-news',
    '/domestic-news',
    '/local-news',
    '/jtbc',
    '/kbs',
    '/mbc',
    '/sbs',
    '/ytn',
  ],
  '국제 뉴스': [
    '/world-news',
    '/international',
    '/global-news',
    '/foreign-news',
    '/overseas',
    '/bbc',
    '/cnn',
    '/reuters',
    '/ap',
    '/global-affairs',
  ],
  'IT/테크 뉴스': [
    '/tech-news',
    '/technology',
    '/tech-trend',
    '/gadget-news',
    '/innovation',
    '/digital-news',
    '/it-times',
    '/techcrunch',
    '/wired',
    '/theverge',
  ],
  정치: [
    '/politics',
    '/political-news',
    '/government',
    '/election',
    '/policy',
    '/congress',
    '/parliament',
    '/legislation',
    '/politician',
    '/democracy',
  ],
  '사회 이슈': [
    '/social-issues',
    '/society',
    '/environmental-issues',
    '/climate',
    '/human-rights',
    '/equality',
    '/discrimination',
    '/activism',
    '/social-movement',
    '/justice',
  ],
  // 기타
  기타: [
    '/misc',
    '/etc',
    '/other',
    '/general',
    '/various',
    '/miscellaneous',
    '/unclassified',
    '/uncategorized',
    '/mixed',
    '/diverse',
  ],
};
