export const contentSelectors = [
  'article',
  'main',
  '[role="main"]',
  '#content',
  '.content',
  '[class*="content-main"]',
  '[class*="main-content"]',
  '.post',
  '.entry',
  '[class*="article"]',
  '[id*="article"]',
  '[class*="post"]',
  '[id*="post"]',
  '[class*="blog-post"]',
  '[class*="content-body"]',
  '.documentation',
  '.markdown-body',
  '.readme',
  '.wiki-content',
  '.prose',
];

export const techSelectors = [
  '.documentation',
  '.markdown-body',
  '.readme',
  '.wiki-content',
  '[class*="docs"]',
  '[id*="docs"]',
  '[class*="api"]',
  '[id*="api"]',
  '[class*="tech"]',
  '[id*="tech"]',
  '.code-example',
  '[class*="tutorial"]',
];
