name: Docker Image CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        env:
          GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
          GHCR_PASSWORD: ${{secrets.GHCR_PASSWORD}}

        run: docker login ghcr.io -u $GHCR_USERNAME --password $GHCR_PASSWORD
      - name: Build the Docker image
        run: docker build -t capstone .
      - name: taging
        run: docker tag capstone:latest ghcr.io/wlstmd/capstone:latest
      - name: Push to GitHub Container Registry
        run: docker push wlstmd/capstone:latest
